name: Branch Name Validator

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches-ignore:
      - main

jobs:
  validate-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name format
        run: |
          BRANCH_NAME=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          echo "Checking branch name: $BRANCH_NAME"
          
          # Check if branch name follows the format dd-mm-yyyy/username/app-name
          # For example: 01-05-2025/dudutwizer/portfolio-app
          if ! [[ $BRANCH_NAME =~ ^[0-9]{2}-[0-9]{2}-[0-9]{4}/[^/]+/[^/]+$ ]]; then
            echo "❌ ERROR: Branch name does not follow the required format!"
            echo "Branch name should be: dd-mm-yyyy/username/app-name"
            echo "For example: 01-05-2025/dudutwizer/portfolio-app"
            exit 1
          else
            echo "✅ Branch name format is valid: $BRANCH_NAME"
            
            # Extract parts from branch name
            DATE=$(echo $BRANCH_NAME | cut -d'/' -f1)
            USERNAME=$(echo $BRANCH_NAME | cut -d'/' -f2)
            APP_NAME=$(echo $BRANCH_NAME | cut -d'/' -f3)
            
            echo "Date: $DATE"
            echo "Username: $USERNAME"
            echo "App name: $APP_NAME"
          fi 