on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.APPS_BY_AGENTS_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.APPS_BY_AGENTS_AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-west-2
    steps:
      - uses: actions/checkout@v1
      - name: Deploy
        uses: lbertenasco/s3-deploy@v1
        with:
          folder: ./
          bucket: xpander-apps-by-agents
          dist-id: E16BHFHGUUBP5P
          invalidation: / *
