name: Deploy Static Website to S3 and Invalidate CloudFront

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to S3 and Invalidate CDN
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.APPS_BY_AGENTS_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.APPS_BY_AGENTS_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Sync files to S3
        run: |
          aws s3 sync ./public s3://xpander-apps-by-agents --delete --acl public-read

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E16BHFHGUUBP5P \
            --paths "/*"
