name: Generate Projects and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.APPS_BY_AGENTS_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.APPS_BY_AGENTS_AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-west-2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate links and inject into template
        run: |
          LINKS=$(find . -type f -name index.html ! -path "./index.html" | while read path; do
            dir=$(dirname "$path")
            title=$(basename "$dir")
            href="${dir#./}/"
            echo "    <li><a href=\"$href\" title=\"$title\">$href</a></li>"
          done)

          COUNT=$(echo "$LINKS" | wc -l)

          # Safely inject links and project count into templates
          awk -v links="$LINKS" -v count="$COUNT" '
            /{{links}}/ { gsub("{{links}}", links) }
            /{{count}}/ { gsub("{{count}}", count) }
            { print }
          ' projects.html > projects.tmp.html && mv projects.tmp.html projects.html

          # Safely inject project count into index.html
          awk -v count="$COUNT" '
            /{{count}}/ { gsub("{{count}}", count) }
            { print }
          ' index.html > index.tmp.html && mv index.tmp.html index.html

      - name: Deploy to AWS S3 + CloudFront
        uses: lbertenasco/s3-deploy@v1
        with:
          folder: ./
          bucket: xpander-apps-by-agents
          dist-id: E16BHFHGUUBP5P
          invalidation: "/*"
