name: AI Agent Contribution Validation

on:
  pull_request:
    branches: [ main ]

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check branch naming convention
        run: |
          BRANCH_NAME=${GITHUB_HEAD_REF}
          # Check if the branch follows the pattern dd-mm-yyyy/username/app-name
          if ! [[ $BRANCH_NAME =~ ^[0-9]{2}-[0-9]{2}-[0-9]{4}/[^/]+/[^/]+$ ]]; then
            echo "Branch naming doesn't follow the pattern dd-mm-yyyy/username/app-name"
            echo "Your branch: $BRANCH_NAME"
            echo "Example format: 01-05-2025/dudutwizer/portfolio-app"
            exit 1
          fi

      - name: Validate directory structure
        run: |
          BRANCH_NAME=${GITHUB_HEAD_REF}
          # Extract parts from branch name
          DATE=$(echo $BRANCH_NAME | cut -d'/' -f1)
          USERNAME=$(echo $BRANCH_NAME | cut -d'/' -f2)
          APP_NAME=$(echo $BRANCH_NAME | cut -d'/' -f3)
          
          # Check if the correct directory structure exists
          if [ ! -d "$DATE/$USERNAME/$APP_NAME" ]; then
            echo "Directory structure does not match the branch name"
            echo "Expected directory: $DATE/$USERNAME/$APP_NAME"
            exit 1
          fi
      
      - name: Verify AI acknowledgment
        run: |
          BRANCH_NAME=${GITHUB_HEAD_REF}
          # Extract parts from branch name
          DATE=$(echo $BRANCH_NAME | cut -d'/' -f1)
          USERNAME=$(echo $BRANCH_NAME | cut -d'/' -f2)
          APP_NAME=$(echo $BRANCH_NAME | cut -d'/' -f3)
          
          # Check if README.md exists and contains AI acknowledgment
          if [ ! -f "$DATE/$USERNAME/$APP_NAME/README.md" ]; then
            echo "README.md is missing from the project directory"
            exit 1
          fi
          
          # Check if README mentions it was created by an AI
          if ! grep -q -i "AI\|agent\|generated\|created" "$DATE/$USERNAME/$APP_NAME/README.md"; then
            echo "README.md should acknowledge that the application was created by an AI agent"
            exit 1
          fi 